version: '3'
services:
  ai-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ai-server
    volumes:
      - /nv/projects/modelscope:/app
      - /root/.cache/modelscope:/mnt/workspace/.cache/modelscope
    container_name: ai-server
    ports:
      - 8000:8000