version: '3'
services:
  ai-server:
    build:
      dockerfile: Dockerfile
    image: ai-server
    volumes:
      - /home/ratel/test/logs:/logs
      - /root/.cache/modelscope:/mnt/workspace/.cache/modelscope
    container_name: ai-server
    ports:
      - 8000:8000